# Generated by Django 4.2.27 on 2026-01-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('STOCKS', 'Actions'), ('CRYPTO', 'Crypto'), ('FIAT', 'Monnaie Fiat'), ('REAL_ESTATE', 'Immobilier')], max_length=20),
        ),
        migrations.AlterField(
            model_name='holding',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manuel'), ('API', 'API')], default='MANUAL', max_length=20),
        ),
    ]
