# Generated by Django 4.2.27 on 2026-01-04 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0002_alter_asset_category_alter_holding_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(choices=[('INCOME', 'Revenu'), ('EXPENSE', 'Dépense'), ('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait')], default='EXPENSE', max_length=20)),
                ('category', models.CharField(help_text='Catégorie (ex: Alimentation, Salaire)', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('MANUAL', 'Manuel'), ('WEBHOOK', 'Automatisé (Webhook)')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
